### ISSUE TITLE
Chinese Market - PIN code request is not working

### ISSUE THREAD

**Issue by harlonjo** [ReneNulschDE/mbapi2020#157] opened 2023-12-11 15:04 UTC
sensors offine suddenly

**Comment by ReneNulschDE** [comment] 2023-12-11 15:26
Hi @harlonjo ,

please take the time to explain your problem properly - Standing on the market and shouting that something is not working does not echo with a valid answer.

what do you do?
What is your setup?
What is not working?
What have you tried already?
What are the errors in the log?
What elso do you know that could help me to answer your question?

BR
Rene

**Comment by harlonjo** [comment] 2023-12-12 08:33
Still can't receive PIN code(six numbers) after I login my mercedes me account, it worked before yesterday and sensors were created normally

**Comment by ReneNulschDE** [comment] 2023-12-12 08:42
Hi, its not a general problem with the component, I received several PINs today. Without a detailed error-log its impossible to help. Please try first to use the MB mobile app. Logout and login in the mobile app and check if its working in the app.

**Comment by harlonjo** [comment] 2023-12-12 08:53
It worked in app during the component worked with problem, how can I provide error logs to you. I may try to reinstall the component first.

**Comment by ReneNulschDE** [comment] 2023-12-12 09:07
Hi,

Are you really sure that you logged-out in the MB app and logged-in again to test the PIN process? If yes, did you checked your Spam Folder? The PIN code process is quite simple. As long as the email-address is correct and you selected the right region, it should work.

To enable the logging:
1. Goto the integration page of MBAPI2020 and click on "Enable debug logging".
2. Restart HA
3. Reauthenticate the integration
4. Goto the integration page of MBAPI2020 and click on "Disable debug logging", save the file and send the file to mb.dev.issue157@nulsch.de

**Comment by harlonjo** [comment] 2023-12-12 09:21
I'm sure that I logged-out in the MB app and logged-in again to test the PIN process, it's still working on my phone. I tried to use my email, but I can't fine PIN neither in my inbox, nor in my spam folder.
 I used my phone number to logged-in with +86, and selected CN, it did work before.
Now, I'm not able to go to the integration page, because I can't reauthenticate the integration. 
/sad face
@ReneNulschDE

**Comment by ReneNulschDE** [comment] 2023-12-12 10:07
You are from China? 

You can enable the debug logging via the configuration.yaml too, see the readme at the end - but I expect that something has changed in your region.

**Comment by harlonjo** [comment] 2023-12-13 00:47
Oh...I just configurated my car dashboard in HA, did even not use it for 1 day... @ReneNulschDE ![QQ截图20231213084721](https://github.com/ReneNulschDE/mbapi2020/assets/56776619/a16c7be9-3177-4c3a-ba0f-89831929610d)

**Comment by ReneNulschDE** [comment] 2023-12-13 14:32
@harlonjo : Could you please share the debug log?

**Comment by harlonjo** [comment] 2023-12-14 09:04
OK, I try to get my debug log. @ReneNulschDE

**Comment by SolarZom** [comment] 2024-01-17 08:08
I'm a Chinese user and I can't get my PIN either。

Logger: custom_components.mbapi2020.oauth
Source: custom_components/mbapi2020/oauth.py:224
Integration: MercedesME 2020 (documentation, issues)
First occurred: 15:59:17 (1 occurrences)
Last logged: 15:59:17

ClientError requesting data from https://ciam-1.mercedes-benz.com.cn/as/token.oauth2: 400, message='Bad Request', url=URL('https://ciam-1.mercedes-benz.com.cn/as/token.oauth2')

**Comment by ReneNulschDE** [comment] 2024-01-17 08:44
Hi @SolarZom ,

unfortunately, I have no access to any Chinese car and therefor I can't test this currently. 

I have an idea what the problem is, but I need a Chinese user to test this.

What is your technical level? Could you change some easy points in the source code and restart HA?

**Comment by SolarZom** [comment] 2024-01-18 03:15
Hi @ReneNulschDE ,I am very happy to assist you, but my technical level may not be enough. You can tell me what needs to be modified, and I can try it out as much as I can.

**Comment by ReneNulschDE** [comment] 2024-02-07 11:58
Please check this link:
https://github.com/ReneNulschDE/mbapi2020/issues/184#issuecomment-1930897256

This should solve the problem with china too.

**Comment by ReneNulschDE** [comment] 2024-02-08 20:48
fixed with v0.10.1

**Closed by ReneNulschDE** 2024-02-08 20:48 UTC
Labels: need-more-information
